In [37]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn import metrics
from sklearn import preprocessing

from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
features=["Gender","Married","Dependents","Education","Self_Employed","ApplicantIncome","CoapplicantIncome","LoanAmount","Loan_Amount_Term","Credit_History","Property_Area"]

In [3]:
data=pd.read_csv('Data Sets/DataSet.csv')
data.head()

Loan_ID Gender Married  Dependents     Education Self_Employed  \
0  LP001002   Male      No           0      Graduate            No   
1  LP001003   Male     Yes           1      Graduate            No   
2  LP001005   Male     Yes           0      Graduate           Yes   
3  LP001006   Male     Yes           0  Not Graduate            No   
4  LP001008   Male      No           0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               11                  0           2               360   
1                8                  5           8               360   
2                4                  0           2               360   
3                3                 10           7               360   
4               11                  0          10               360   

   Credit_History Property_Area Loan_Status  
0               1         Urban           Y  
1               1         Rural           N  
2               1         Urban           Y  
3               1         Urban           Y  
4               1         Urban           Y

In [4]:
loan_encoder = preprocessing.LabelEncoder()
data['Gender'] = loan_encoder.fit_transform(data['Gender'])
data['Married'] = loan_encoder.fit_transform(data['Married'])
data['Dependents']=loan_encoder.fit_transform(data['Dependents'])
data['Education'] = loan_encoder.fit_transform(data['Education'])
data['Self_Employed'] = loan_encoder.fit_transform(data['Self_Employed'])
data['Property_Area'] = loan_encoder.fit_transform(data['Property_Area'])
data['Loan_Status'] = loan_encoder.fit_transform(data['Loan_Status'])
data.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0  LP001002       1        0           0          0              0   
1  LP001003       1        1           1          0              0   
2  LP001005       1        1           0          0              1   
3  LP001006       1        1           0          1              0   
4  LP001008       1        0           0          0              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               11                  0           2               360   
1                8                  5           8               360   
2                4                  0           2               360   
3                3                 10           7               360   
4               11                  0          10               360   

   Credit_History  Property_Area  Loan_Status  
0               1              2            1  
1               1              0            0  
2               1              2            1  
3               1              2            1  
4               1              2            1

In [5]:
train, test = train_test_split(data, test_size = 0.25)
print("Training Data Size: {}; Test Size: {}".format(len(train),len(test)))

Training Data Size: 460; Test Size: 154


In [25]:
x=data.iloc[:,1:12]
y =data.iloc[:,12:13]

In [26]:
y.head()

Loan_Status
0            1
1            0
2            1
3            1
4            1

In [28]:
X = data[features]
y = data.Loan_Status
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [30]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [33]:
X_train

array([[ 0.46575875,  0.70250017, -0.78161751, ...,  0.31020444,
         0.41649656, -1.31684978],
       [ 0.46575875,  0.70250017, -0.78161751, ...,  0.31020444,
         0.41649656, -1.31684978],
       [ 0.46575875,  0.70250017, -0.78161751, ...,  0.31020444,
         0.41649656, -0.0574924 ],
       ...,
       [ 0.46575875,  0.70250017,  2.1257468 , ...,  0.31020444,
         0.41649656,  1.20186498],
       [ 0.46575875,  0.70250017, -0.78161751, ...,  0.31020444,
         0.41649656, -0.0574924 ],
       [ 0.46575875,  0.70250017,  1.15662537, ...,  0.31020444,
         0.41649656,  1.20186498]])

In [132]:
#By default the 'relu' activation function is used with 'adam' cost optimizer.
mlp1 = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1900, alpha=0.001, solver='sgd', learning_rate='adaptive')
mlp1.fit(X_train, y_train.values.ravel())

MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 10, 10), learning_rate='adaptive',
              learning_rate_init=0.001, max_iter=1900, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='sgd', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [133]:
predictions = mlp1.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[ 27  21]
 [  5 101]]
              precision    recall  f1-score   support

           0       0.84      0.56      0.68        48
           1       0.83      0.95      0.89       106

    accuracy                           0.83       154
   macro avg       0.84      0.76      0.78       154
weighted avg       0.83      0.83      0.82       154



In [134]:
mlp2 = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1900,activation='identity', alpha=0.001, solver='sgd', learning_rate='adaptive')
mlp2.fit(X_train, y_train.values.ravel())
predictions = mlp2.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[ 29  19]
 [  4 102]]
              precision    recall  f1-score   support

           0       0.88      0.60      0.72        48
           1       0.84      0.96      0.90       106

    accuracy                           0.85       154
   macro avg       0.86      0.78      0.81       154
weighted avg       0.85      0.85      0.84       154



In [142]:
mlp3 = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1900,activation='logistic', alpha=0.001, solver='sgd', learning_rate='adaptive')
mlp3.fit(X_train, y_train.values.ravel())
predictions = mlp3.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[  0  48]
 [  0 106]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        48
           1       0.69      1.00      0.82       106

    accuracy                           0.69       154
   macro avg       0.34      0.50      0.41       154
weighted avg       0.47      0.69      0.56       154



H:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [143]:
mlp4 = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1900,activation='tanh', alpha=0.001, solver='sgd', learning_rate='adaptive')
mlp4.fit(X_train, y_train.values.ravel())
predictions = mlp4.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[ 29  19]
 [  6 100]]
              precision    recall  f1-score   support

           0       0.83      0.60      0.70        48
           1       0.84      0.94      0.89       106

    accuracy                           0.84       154
   macro avg       0.83      0.77      0.79       154
weighted avg       0.84      0.84      0.83       154

