In [2]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

%matplotlib inline

In [3]:
data=pd.read_csv('Data Sets/DataSet.csv')
data.head()

Loan_ID Gender Married  Dependents     Education Self_Employed  \
0  LP001002   Male      No           0      Graduate            No   
1  LP001003   Male     Yes           1      Graduate            No   
2  LP001005   Male     Yes           0      Graduate           Yes   
3  LP001006   Male     Yes           0  Not Graduate            No   
4  LP001008   Male      No           0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               11                  0           2               360   
1                8                  5           8               360   
2                4                  0           2               360   
3                3                 10           7               360   
4               11                  0          10               360   

   Credit_History Property_Area Loan_Status  
0               1         Urban           Y  
1               1         Rural           N  
2               1         Urban           Y  
3               1         Urban           Y  
4               1         Urban           Y

In [4]:
data.shape

(614, 13)

In [5]:
loan_encoder = preprocessing.LabelEncoder()
data['Gender'] = loan_encoder.fit_transform(data['Gender'])
data['Married'] = loan_encoder.fit_transform(data['Married'])
data['Dependents']=loan_encoder.fit_transform(data['Dependents'])
data['Education'] = loan_encoder.fit_transform(data['Education'])
data['Self_Employed'] = loan_encoder.fit_transform(data['Self_Employed'])
data['Property_Area'] = loan_encoder.fit_transform(data['Property_Area'])
data['Loan_Status'] = loan_encoder.fit_transform(data['Loan_Status'])
data.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0  LP001002       1        0           0          0              0   
1  LP001003       1        1           1          0              0   
2  LP001005       1        1           0          0              1   
3  LP001006       1        1           0          1              0   
4  LP001008       1        0           0          0              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               11                  0           2               360   
1                8                  5           8               360   
2                4                  0           2               360   
3                3                 10           7               360   
4               11                  0          10               360   

   Credit_History  Property_Area  Loan_Status  
0               1              2            1  
1               1              0            0  
2               1              2            1  
3               1              2            1  
4               1              2            1

In [6]:
x=data.iloc[:,1:12]
y =data.iloc[:,12:13]

In [7]:
x.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           0          0              0               11   
1       1        1           1          0              0                8   
2       1        1           0          0              1                4   
3       1        1           0          1              0                3   
4       1        0           0          0              0               11   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0           2               360               1   
1                  5           8               360               1   
2                  0           2               360               1   
3                 10           7               360               1   
4                  0          10               360               1   

   Property_Area  
0              2  
1              0  
2              2  
3              2  
4              2

In [8]:
y.head()

Loan_Status
0            1
1            0
2            1
3            1
4            1

In [9]:
features=["Gender","Married","Dependents","Education","Self_Employed","ApplicantIncome","CoapplicantIncome","LoanAmount","Loan_Amount_Term","Credit_History","Property_Area"]
X = data[features]
y = data.Loan_Status
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [10]:
svclassifier1 = SVC(kernel='linear',gamma='auto',class_weight='balanced')
svclassifier1.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight='balanced', coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [11]:
y_pred = svclassifier1.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 21  23]
 [  1 109]]
              precision    recall  f1-score   support

           0       0.95      0.48      0.64        44
           1       0.83      0.99      0.90       110

    accuracy                           0.84       154
   macro avg       0.89      0.73      0.77       154
weighted avg       0.86      0.84      0.83       154



In [13]:
svclassifier2 = SVC(kernel='poly',gamma='auto',class_weight='balanced')
svclassifier2.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight='balanced', coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [14]:
y_pred = svclassifier2.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[26 18]
 [29 81]]
              precision    recall  f1-score   support

           0       0.47      0.59      0.53        44
           1       0.82      0.74      0.78       110

    accuracy                           0.69       154
   macro avg       0.65      0.66      0.65       154
weighted avg       0.72      0.69      0.70       154



In [15]:
svclassifier3 = SVC(kernel='rbf',gamma='auto',class_weight='balanced')
svclassifier3.fit(X_train, y_train)
y_pred = svclassifier3.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[27 17]
 [31 79]]
              precision    recall  f1-score   support

           0       0.47      0.61      0.53        44
           1       0.82      0.72      0.77       110

    accuracy                           0.69       154
   macro avg       0.64      0.67      0.65       154
weighted avg       0.72      0.69      0.70       154



In [16]:
svclassifier4 = SVC(kernel='sigmoid',gamma='auto',class_weight='balanced')
svclassifier4.fit(X_train, y_train)
y_pred = svclassifier4.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[  0  44]
 [  0 110]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        44
           1       0.71      1.00      0.83       110

    accuracy                           0.71       154
   macro avg       0.36      0.50      0.42       154
weighted avg       0.51      0.71      0.60       154



H:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
